### ISSUE TITLE
POPUp Lov - AdvancedSelection

### ISSUE THREAD

**Issue by mohamedyounis30002000** [GabrielZambonidaSilva/pluginsOracleApex#1]
Hello 

I try this awesome **_(POPUp Lov - AdvancedSelection)_** and it working very well but when i open the form for exist row it show <group row> words as the attached image

but if i re select this words gone .. or if i create new this words not shown , only when i open exist row 

`it will be great if you help
`

![Uploading POP.png…]()

**Comment by mohamedyounis30002000** [comment]
[https://www.mediafire.com/view/8o4qgqxmxwzq0ms/POP.png/file](url)

**Comment by GabrielZambonidaSilva** [comment]
Hello,
Send me images of the settings and query you are doing, so I can help you better.
I also need the advanced options -> classes

**Comment by mohamedyounis30002000** [comment]
Hello ,
Thanks for your kind support and prompt action ,  Kindly find the below
images

[image: image.png]

[image: image.png]




‫في الأربعاء، 1 فبراير 2023 في 3:00 م تمت كتابة ما يلي بواسطة
‪GabrielZambonidaSilva‬‏ ***@***.***‬‏>:‬

**Comment by GabrielZambonidaSilva** [comment]
I couldn't open the images, can you put it on a shared google drive and send me the link?

**Comment by mohamedyounis30002000** [comment]
Sure, here you go!
https://drive.google.com/drive/folders/1kEopo2aCawdKo6OOYNM1E6mTH7-yPI9g?usp=sharing

‫في الأربعاء، 1 فبراير 2023 في 3:44 م تمت كتابة ما يلي بواسطة
‪GabrielZambonidaSilva‬‏ ***@***.***‬‏>:‬

**Comment by GabrielZambonidaSilva** [comment]
I need images the plugin configuration in global page

**Comment by mohamedyounis30002000** [comment]
I'm sorry I couldn't understand what I should do

**Comment by mohamedyounis30002000** [comment]
I'm sorry for the previous reply
i add the image to the drive folder
https://drive.google.com/drive/folders/1kEopo2aCawdKo6OOYNM1E6mTH7-yPI9g?usp=sharing

‫في الأربعاء، 1 فبراير 2023 في 4:04 م تمت كتابة ما يلي بواسطة ‪mohamed
younis elshamy‬‏ ***@***.***‬‏>:‬

> I'm sorry I couldn't understand what I should do
>
> On Wed, Feb 1, 2023, 3:54 PM GabrielZambonidaSilva <

**Comment by GabrielZambonidaSilva** [comment]
Send message in my Whats App - [Zamboni](https://wa.me/+5554999655497)

**Comment by GabrielZambonidaSilva** [comment]
Test Please - Import the plugin with the correction

**Comment by mohamedyounis30002000** [comment]
I would like to inform you that everything is now working efficiently and I would like to thank you for this wonderful effort
